import { ArrowLeft, ArrowRight, BookOpen, Clock3, Dna, FileText, Pencil, Sparkles, Trash2, Users } from "lucide-react";
import type { Book } from "@/lib/types";
import { BrandLogo } from "./BrandLogo";

interface Props { book: Book; onBack: () => void; onStartWriting: () => void; onChange: (book: Book) => void; onDelete: () => void }
export function BlueprintView({ book, onBack, onStartWriting, onChange, onDelete }: Props) {
  const updateChapter = (id: string, key: "title" | "summary", value: string) => onChange({ ...book, chapters: book.chapters.map((chapter) => chapter.id === id ? { ...chapter, [key]: value } : chapter) });
  const totalWords = book.targetWords;
  return <div className="studio-page"><header className="studio-header"><button className="brand" onClick={onBack}><BrandLogo priority /></button><div className="studio-title"><span>Book Blueprint</span><strong>{book.title}</strong></div><div className="studio-actions"><button className="delete-draft-action" onClick={onDelete}><Trash2 size={15} /> Delete Draft</button><button className="primary-button" onClick={onStartWriting}>Open Chapter Studio <ArrowRight size={16} /></button></div></header>
    <main className="blueprint-shell"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Author Workspace</button><section className="blueprint-hero"><div><p className="eyebrow"><Sparkles size={14} /> YOUR BOOK BLUEPRINT</p><h1>Your idea now has a shape.</h1><p>Review the promise, voice, and chapter journey before you begin writing. Every title and summary is editable.</p></div><div className="blueprint-stats"><span><FileText size={19} /><small>Estimated length</small><strong>{book.targetPageCount} pages</strong></span><span><Clock3 size={19} /><small>Reading time</small><strong>{Math.round(book.targetPageCount * 1.5)} minutes</strong></span><span><BookOpen size={19} /><small>Target words</small><strong>{totalWords.toLocaleString()} words</strong></span></div></section>
      <section className="blueprint-grid"><div className="blueprint-main"><article className="synopsis-card"><div className="card-heading"><span><BookOpen size={19} /></span><div><p className="eyebrow">BOOK SYNOPSIS</p><h2>The promise of your book</h2></div></div><p><strong>{book.title}</strong> by {book.authorName}</p><p>{book.idea}</p><blockquote>“{book.bookDna.promise}”</blockquote></article><div className="toc-heading"><div><p className="eyebrow">TABLE OF CONTENTS</p><h2>The reader’s journey</h2></div><span>{book.chapters.length} chapters</span></div><div className="chapter-plan-list">{book.chapters.map((chapter) => <article key={chapter.id}><span className="chapter-number">{String(chapter.chapterNumber).padStart(2,"0")}</span><div><label><input value={chapter.title} onChange={(event) => updateChapter(chapter.id, "title", event.target.value)} /><Pencil size={13} /></label><textarea value={chapter.summary} onChange={(event) => updateChapter(chapter.id, "summary", event.target.value)} /><div className="outline-chips">{chapter.outline.map((point) => <span key={point}>{point}</span>)}</div></div><small>{chapter.targetWordCount.toLocaleString()} words · {Math.ceil(chapter.targetWordCount / book.wordsPerPage)} pages</small></article>)}</div></div>
        <aside className="dna-card"><div className="card-heading"><span><Dna size={19} /></span><div><p className="eyebrow">BOOK DNA</p><h2>Your creative compass</h2></div></div><div className="dna-item"><small>Core promise</small><p>{book.bookDna.promise}</p></div><div className="dna-item"><small><Users size={13} /> Ideal reader</small><p>{book.targetAudience}</p></div><div className="dna-item"><small>Tone & voice</small><p>{book.bookDna.tone}</p><p>{book.bookDna.voice}</p></div><div className="dna-item"><small>Core themes</small><div className="theme-list">{book.bookDna.themes.map((theme) => <span key={theme}>{theme}</span>)}</div></div><div className="dna-item"><small>Writing rules</small><ul>{book.bookDna.styleRules.map((rule) => <li key={rule}>{rule}</li>)}</ul></div><div className="dna-item"><small>COVER CONCEPT</small><p>{book.coverPrompt}</p></div><button className="primary-button full" onClick={onStartWriting}>Start Writing Chapter One <ArrowRight size={16} /></button><p className="reassurance">Your Book DNA stays active across every chapter.</p></aside>
      </section></main></div>;
}
