import { BrandMark } from "@/components/BrandMark";
import { ArrowLeft, ArrowRight, BookOpen, Clock3, Dna, FileText, Lock, Pencil, RefreshCcw, Sparkles, Trash2, Unlock, Users } from "lucide-react";
import { buildChapterTitleContext, generateChapterTitleOptions, regenerateTitleOptionsForChapter, titleQuality } from "@/lib/chapter-title-intelligence";
import type { Book, Chapter, ChapterTitleOption } from "@/lib/types";

interface Props { book: Book; onBack: () => void; onStartWriting: () => void; onChange: (book: Book) => void; onDelete: () => void }

export function BlueprintView({ book, onBack, onStartWriting, onChange, onDelete }: Props) {
  const patchChapter = (id: string, patch: Partial<Chapter>) => onChange({ ...book, chapters: book.chapters.map((chapter) => chapter.id === id ? { ...chapter, ...patch } : chapter) });
  const editTitle = (chapter: Chapter, value: string) => {
    const titleContext = buildChapterTitleContext(value, book.bookDna, chapter.summary);
    patchChapter(chapter.id, { title: value, selectedTitle: value, titleContext, chapterPromise: titleContext.chapterPromise, suggestedOpeningStyle: titleContext.suggestedOpeningStyle, emotionalDirection: titleContext.emotionalDirection, openingStyle: titleContext.suggestedOpeningStyle, titleQuality: titleQuality(value, book.bookDna, chapter.summary) });
  };
  const selectTitle = (chapter: Chapter, option: ChapterTitleOption) => patchChapter(chapter.id, { title: option.title, selectedTitle: option.title, titleContext: buildChapterTitleContext(option.title, book.bookDna, chapter.summary), chapterPromise: option.chapterPromise, suggestedOpeningStyle: option.suggestedOpeningStyle, emotionalDirection: option.emotionalDirection, openingStyle: option.suggestedOpeningStyle, titleQuality: titleQuality(option.title, book.bookDna, chapter.summary) });
  const ensureOptions = (chapter: Chapter) => chapter.titleOptions?.length ? chapter.titleOptions : generateChapterTitleOptions(book.bookDna, chapter.summary, chapter.chapterNumber - 1);
  const regenerate = (chapter: Chapter) => {
    if (chapter.titleLocked) return;
    const titleOptions = regenerateTitleOptionsForChapter(book.bookDna, { ...chapter, titleOptions: ensureOptions(chapter) });
    patchChapter(chapter.id, { titleOptions });
  };
  return <div className="studio-page"><header className="studio-header"><button className="brand" onClick={onBack}><BrandMark /><span><strong>Clarity Loop</strong><small>AI BOOK STUDIO</small></span></button><div className="studio-title"><span>Book Blueprint</span><strong>{book.title}</strong></div><div className="studio-actions"><button className="delete-draft-action" onClick={onDelete}><Trash2 size={15} /> Delete Draft</button><button className="primary-button" onClick={onStartWriting}>Open Chapter Studio <ArrowRight size={16} /></button></div></header>
    <main className="blueprint-shell"><button className="back-link" onClick={onBack}><ArrowLeft size={15} /> Author Workspace</button><section className="blueprint-hero"><div><p className="eyebrow"><Sparkles size={14} /> YOUR BOOK BLUEPRINT</p><h1>Your idea now has a shape.</h1><p>Review the promise, voice, and chapter journey before you begin writing. Every title and summary is editable.</p>{book.genreWarnings?.length ? <div className="identity-warning">{book.genreWarnings.join(" ")}</div> : null}</div><div className="blueprint-stats"><span><FileText size={19} /><small>Estimated length</small><strong>{book.targetPageCount} pages</strong></span><span><Clock3 size={19} /><small>Reading time</small><strong>{Math.round(book.targetPageCount * 1.5)} minutes</strong></span><span><BookOpen size={19} /><small>Genre alignment</small><strong>{book.genreAlignmentScore ?? 100}%</strong></span></div></section>
      <section className="blueprint-grid"><div className="blueprint-main"><article className="synopsis-card"><div className="card-heading"><span><BookOpen size={19} /></span><div><p className="eyebrow">BOOK SYNOPSIS</p><h2>The promise of your book</h2></div></div><p><strong>{book.title}</strong> by {book.authorName}</p><p>{book.idea}</p><blockquote>“{book.bookDna.promise}”</blockquote></article><div className="toc-heading"><div><p className="eyebrow">TABLE OF CONTENTS</p><h2>The reader’s journey</h2></div><span>{book.chapters.length} chapters</span></div><div className="chapter-plan-list">{book.chapters.map((chapter) => {
        const options = ensureOptions(chapter);
        const quality = chapter.titleQuality || titleQuality(chapter.selectedTitle || chapter.title, book.bookDna, chapter.summary);
        return <article key={chapter.id}><span className="chapter-number">{String(chapter.chapterNumber).padStart(2,"0")}</span><div><label><input value={chapter.selectedTitle || chapter.title} disabled={chapter.titleLocked} onChange={(event) => editTitle(chapter, event.target.value)} /><Pencil size={13} /></label><div className="title-actions"><span className={`title-quality ${quality.toLowerCase().replace(" ", "-")}`}>{quality}</span><button onClick={() => patchChapter(chapter.id, { titleLocked: !chapter.titleLocked })}>{chapter.titleLocked ? <Unlock size={12} /> : <Lock size={12} />} {chapter.titleLocked ? "Unlock title" : "Lock title"}</button><button disabled={chapter.titleLocked} onClick={() => regenerate(chapter)}><RefreshCcw size={12} /> New options</button></div><details className="title-intelligence"><summary>View {options.length} genre-aware title options</summary><div className="title-option-list">{options.map((option) => <button className="title-option" key={option.title} onClick={() => selectTitle(chapter, option)}><strong>{option.title}</strong><span>{option.genreFitScore}% fit</span><small>{option.rationale}</small></button>)}</div></details><textarea value={chapter.summary} onChange={(event) => patchChapter(chapter.id, { summary: event.target.value })} /><div className="outline-chips">{chapter.outline.map((point) => <span key={point}>{point}</span>)}</div></div><small>{chapter.targetWordCount.toLocaleString()} words · {Math.ceil(chapter.targetWordCount / book.wordsPerPage)} pages</small></article>;
      })}</div></div>
        <aside className="dna-card"><div className="card-heading"><span><Dna size={19} /></span><div><p className="eyebrow">BOOK DNA</p><h2>Your creative compass</h2></div></div><div className="dna-item"><small>Book type & creative mode</small><p>{book.bookDna.genreProfile?.label || book.genre}</p><p>{book.bookDna.creativeMode?.replaceAll("_", " ")}</p></div><div className="dna-item"><small>Core promise</small><p>{book.bookDna.promise}</p></div><div className="dna-item"><small><Users size={13} /> Ideal reader</small><p>{book.targetAudience}</p></div><div className="dna-item"><small>Tone & voice</small><p>{book.bookDna.tone}</p><p>{book.bookDna.voice}</p></div><div className="dna-item"><small>Required creative elements</small><div className="theme-list">{(book.bookDna.requiredElements || book.bookDna.themes).map((theme) => <span key={theme}>{theme}</span>)}</div></div><div className="dna-item"><small>Writing rules</small><ul>{book.bookDna.styleRules.map((rule) => <li key={rule}>{rule}</li>)}</ul></div><div className="dna-item"><small>COVER CONCEPT</small><p>{book.coverPrompt}</p></div><button className="primary-button full" onClick={onStartWriting}>Start Writing Chapter One <ArrowRight size={16} /></button><p className="reassurance">Your Book DNA and chosen titles stay active across every chapter.</p></aside>
      </section></main></div>;
}
