import { ArrowLeft, BookOpen, Check, ChevronLeft, ChevronRight, Download, Expand, Lock, PanelLeftClose, RefreshCcw, Save, Scissors, Sparkles, Trash2, Unlock } from "lucide-react";
import { useState } from "react";
import { countWords } from "@/lib/book-budget";
import { analyzeChapterQuality } from "@/lib/quality";
import type { Book, Chapter } from "@/lib/types";
import { BrandLogo } from "./BrandLogo";
import { ManuscriptProgress } from "./ManuscriptProgress";

interface Props { book: Book; lastSaved: string; onSave: () => void; onBack: () => void; onBlueprint: () => void; onChange: (book: Book) => void; onExport: () => void; onDelete: () => void }
export function ChapterStudio({ book, lastSaved, onSave, onBack, onBlueprint, onChange, onExport, onDelete }: Props) {
  const [activeId, setActiveId] = useState(book.chapters.find((chapter) => !chapter.locked)?.id ?? book.chapters[0]?.id); const [working, setWorking] = useState(false); const [sidebarOpen, setSidebarOpen] = useState(true);
  const chapter = book.chapters.find((item) => item.id === activeId) ?? book.chapters[0];
  const index = book.chapters.findIndex((item) => item.id === chapter?.id);
  const wordCount = chapter ? countWords(chapter.content) : 0;
  const patchChapter = (patch: Partial<Chapter>) => onChange({ ...book, status: "drafting", chapters: book.chapters.map((item) => item.id === chapter.id ? { ...item, ...patch } : item) });
  const updateContent = (content: string) => { const analysis = analyzeChapterQuality({ ...chapter, content }, book.chapters.map((item) => item.id === chapter.id ? { ...item, content } : item)); const words = countWords(analysis.content); patchChapter({ content: analysis.content, actualWordCount: words, estimatedPages: Math.ceil(words / book.wordsPerPage), qualityFlags: analysis.flags, qualityScore: analysis.score, qualityStatus: analysis.status, leakageDetected: analysis.flags.includes("prompt_leakage"), duplicateDetected: analysis.flags.some((flag) => flag.startsWith("duplicate_") || flag === "repeated_phrase"), status: words < chapter.targetWordCount * .85 ? "underdeveloped" : analysis.flags.length ? "needs_review" : "edited" }); };
  const generate = async (action: "write" | "rewrite" | "expand" | "shorten" | "remove_repetition" | "expand_cases" | "regenerate_clean") => { if (chapter.locked) return; setWorking(true); try { const response = await fetch("/api/chapter", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ book, chapter, action }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Chapter generation failed."); patchChapter({ content: data.manuscriptContent, generationContext: data.generationContext, actualWordCount: data.actualWordCount, estimatedPages: data.estimatedPages, status: data.status, qualityFlags: data.qualityFlags || [], qualityScore: data.qualityScore, qualityStatus: data.qualityStatus, leakageDetected: data.leakageDetected, duplicateDetected: data.duplicateDetected }); } finally { setWorking(false); } };
  if (!chapter) return null;
  return <div className="studio-page"><header className="studio-header"><button className="brand" onClick={onBack}><BrandLogo /><span><strong>Clarity Loop</strong><small>AI BOOK STUDIO</small></span></button><div className="studio-title"><span>Chapter Studio</span><strong>{book.title}</strong></div><div className="studio-actions"><button className="delete-draft-action" onClick={onDelete}><Trash2 size={15} /> Delete Draft</button><button className="secondary-button" onClick={onBlueprint}><BookOpen size={16} /> Blueprint</button><button className="primary-button" onClick={onExport}><Download size={16} /> Export Book</button></div></header>
    <div className={`chapter-studio-layout ${sidebarOpen ? "" : "sidebar-closed"}`}><aside className="chapter-sidebar"><div className="sidebar-top"><button className="back-link" onClick={onBack}><ArrowLeft size={14} /> Workspace</button><button aria-label="Close chapter navigation" onClick={() => setSidebarOpen(false)}><PanelLeftClose size={17} /></button></div><div className="sidebar-book"><small>WORKING MANUSCRIPT</small><strong>{book.title}</strong><ManuscriptProgress book={book} compact /></div><div className="chapter-nav-label"><span>Chapters</span><small>{book.chapters.length}</small></div><nav className="chapter-nav">{book.chapters.map((item) => <button className={item.id === chapter.id ? "active" : ""} onClick={() => setActiveId(item.id)} key={item.id}><span>{item.locked ? <Lock size={12} /> : String(item.chapterNumber).padStart(2,"0")}</span><em><strong>{item.title}</strong><small>{item.status === "pending" ? "Ready to write" : item.status === "locked" ? "Approved" : "Draft saved"}</small></em>{item.status !== "pending" && <Check size={14} />}</button>)}</nav><button className="blueprint-link" onClick={onBlueprint}><Sparkles size={15} /> Review Book DNA & blueprint</button></aside>
      <main className="editor-shell">{!sidebarOpen && <button className="open-sidebar" onClick={() => setSidebarOpen(true)}><ChevronRight size={16} /> Chapters</button>}<div className="editor-topbar"><div><p className="eyebrow">CHAPTER {String(chapter.chapterNumber).padStart(2,"0")}</p><input value={chapter.title} onChange={(event) => patchChapter({ title: event.target.value })} disabled={chapter.locked} /></div><div className="chapter-position"><button disabled={index <= 0} onClick={() => setActiveId(book.chapters[index - 1].id)}><ChevronLeft /></button><span>{index + 1} / {book.chapters.length}</span><button disabled={index >= book.chapters.length - 1} onClick={() => setActiveId(book.chapters[index + 1].id)}><ChevronRight /></button></div></div>
        <div className="chapter-brief"><div><Sparkles size={16} /><span><strong>Chapter intention</strong><p>{chapter.summary}</p></span></div><button onClick={() => patchChapter({ locked: !chapter.locked, status: chapter.locked ? "edited" : "locked" })}>{chapter.locked ? <Unlock size={15} /> : <Lock size={15} />}{chapter.locked ? "Unlock chapter" : "Lock chapter"}</button></div>
        <div className="writing-toolbar"><div><button disabled={working || chapter.locked} onClick={() => generate(chapter.content ? "rewrite" : "write")} className="write-button"><Sparkles size={16} /> {working ? "Writing…" : chapter.content ? "Rewrite Chapter" : "Write My Chapter"}</button><button disabled={working || chapter.locked} onClick={() => generate("regenerate_clean")}><RefreshCcw size={15} /> Regenerate Without Padding</button><button disabled={working || chapter.locked || !chapter.content} onClick={() => generate("remove_repetition")}><Scissors size={15} /> Remove Repetition</button><button disabled={working || chapter.locked} onClick={() => generate("expand_cases")}><Expand size={15} /> Expand With Case Studies</button></div><button onClick={onSave}><Save size={14} /> {lastSaved}</button></div>
        <div className="paper-editor"><div className="paper-meta"><span>CHAPTER {chapter.chapterNumber}</span><span>{wordCount.toLocaleString()} / {chapter.targetWordCount.toLocaleString()} words · {Math.max(0, Math.ceil(wordCount / book.wordsPerPage))} pages · {chapter.status}</span></div>{chapter.qualityFlags.length > 0 && <div className="quality-flags"><strong>Quality review</strong>{chapter.qualityFlags.map((flag) => <span key={flag}>{flag.replaceAll("_", " ")}</span>)}</div>}<h1>{chapter.title}</h1>{chapter.content ? <textarea aria-label="Chapter manuscript" value={chapter.content} disabled={chapter.locked} onChange={(event) => updateContent(event.target.value)} /> : <div className="empty-page"><Sparkles size={24} /><h2>Your chapter is ready to begin.</h2><p>Clarity Loop will use your blueprint, chapter outline, and Book DNA to create a thoughtful first draft.</p><button className="primary-button" disabled={working || chapter.locked} onClick={() => generate("write")}><Sparkles size={16} /> {working ? "Writing your chapter…" : "Write My Chapter"}</button><small>Target: {chapter.targetWordCount.toLocaleString()} words · about {chapter.estimatedPages} pages</small></div>}</div>
      </main><aside className="chapter-context"><p className="eyebrow">CHAPTER GUIDE</p><h3>What this chapter needs to do</h3><p>{chapter.summary}</p><div className="context-section"><small>OUTLINE</small><ol>{chapter.outline.map((point) => <li key={point}><span>{chapter.outline.indexOf(point) + 1}</span>{point}</li>)}</ol></div><div className="context-section"><small>CHAPTER-SPECIFIC EXAMPLES</small><ul className="example-bank">{(chapter.exampleBank || []).map((example) => <li key={example}>{example}</li>)}</ul></div><div className="context-section"><small>QUALITY FAILURE DETAILS</small><p>{chapter.qualityFlags.length ? chapter.qualityFlags.map((flag) => flag.replaceAll("_", " ")).join(" · ") : "No fatal quality failures detected."}</p></div><div className="context-section"><small>BOOK DNA IN USE</small><dl><div><dt>Tone</dt><dd>{book.bookDna.tone}</dd></div><div><dt>Reader</dt><dd>{book.bookDna.audience}</dd></div><div><dt>Voice</dt><dd>{book.bookDna.voice}</dd></div></dl></div></aside></div>
  </div>;
}
