import { BarChart3, DatabaseZap, ShieldCheck, TrendingUp } from "lucide-react";
import type { MarketIntelligencePlan } from "@/lib/types";

const confidenceLabel: Record<MarketIntelligencePlan["confidenceLevel"], string> = { verified: "Verified", high_confidence: "High confidence", estimated: "Estimated", low_confidence: "Low confidence" };

export function MarketIntelligenceView({ plan }: { plan: MarketIntelligencePlan }) {
  return <div className="market-intel"><section className="success-panel market-intel-hero"><header><div><p className="success-kicker"><DatabaseZap size={13} /> Book Market Intelligence Engine</p><h2>Lawful market traction signals for author decisions.</h2><p>{plan.formulaSummary}</p></div><span className={`market-confidence ${plan.confidenceLevel}`}>{confidenceLabel[plan.confidenceLevel]}</span></header><div className="overview-metrics"><article><BarChart3 /><span><strong>{plan.marketScore}</strong><small>MarketScore</small></span></article><article><ShieldCheck /><span><strong>{plan.salesConfidenceScore}</strong><small>Sales confidence</small></span></article><article><TrendingUp /><span><strong>{plan.publisherScorecard.score}</strong><small>Publisher lift</small></span></article><article><TrendingUp /><span><strong>{plan.marketingPartnerScorecard.score}</strong><small>Marketer lift</small></span></article></div><div className="ethical-note"><strong>Data integrity guardrail</strong><p>{plan.disclaimer}</p></div></section><section className="success-panel"><header><div><p className="success-kicker">Signal tracker</p><h2>Daily to yearly movement</h2></div></header><div className="market-window-grid">{plan.timeWindows.map((item) => <article key={item.window}><strong>{item.window}</strong><span>{item.confidenceScore}% confidence</span><p>Rank {item.rankVelocity} · Reviews {item.reviewVelocity} · Category {item.categoryMomentum} · Campaign {item.campaignLift}</p></article>)}</div></section><section className="success-panel"><header><div><p className="success-kicker">Attribution scorecards</p><h2>Publishers and marketers with evidence.</h2></div></header><div className="recommendation-grid"><Scorecard title="Publisher Performance Score" card={plan.publisherScorecard} /><Scorecard title="Marketing Partner Scorecard" card={plan.marketingPartnerScorecard} /></div></section><section className="success-panel"><header><div><p className="success-kicker">Compliance-first adapters</p><h2>Source architecture, not a raw scraper.</h2></div></header><div className="asset-grid">{plan.sourceArchitecture.map((source) => <article key={source.name}><small>{source.sourceType.replace("_", " ")} · {source.permission.replaceAll("_", " ")}</small><h3>{source.name}</h3><p>{source.auditRequirement}</p></article>)}</div></section><section className="success-panel"><header><div><p className="success-kicker">Author Decision Brief</p><h2>What to do before spending money.</h2></div></header><div className="asset-grid">{plan.dashboardModules.map((module) => <article key={module}><small>Dashboard module</small><p>{module}</p></article>)}<article className="wide"><small>Recommendations</small>{plan.recommendations.map((item) => <p key={item}>• {item}</p>)}</article></div></section></div>;
}

function Scorecard({ title, card }: { title: string; card: MarketIntelligencePlan["publisherScorecard"] }) {
  return <div><h3>{title}</h3><div className="success-score ready">{card.score}<small>/100</small></div><p><strong>{card.name}</strong> · {confidenceLabel[card.confidence]}</p>{card.evidence.map((item) => <p key={item}>• {item}</p>)}</div>;
}
