import { ArrowLeft, ArrowRight, Check, Sparkles, X } from "lucide-react";
import { useState } from "react";
import type { AIAssistanceLevel, BookForm, BookTemplate, ChapterSizePreference } from "@/lib/types";

const baseForm: BookForm = { title: "", subtitle: "", idea: "", genre: "Self-Help", targetAudience: "", tone: "Encouraging and clear", writingStyle: "Practical and story-led", chapterCount: 10, targetPageCount: 180, chapterSizePreference: "auto", customChapterWords: 2500, aiAssistanceLevel: "guided" };
interface Props { initialTemplate?: BookTemplate | null; onClose: () => void; onCreate: (form: BookForm) => Promise<void> }

export function NewBookWizard({ initialTemplate, onClose, onCreate }: Props) {
  const [step, setStep] = useState(1); const [working, setWorking] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState<BookForm>(() => initialTemplate ? { ...baseForm, genre: initialTemplate.genre, targetAudience: initialTemplate.targetAudience, tone: initialTemplate.tone, writingStyle: initialTemplate.writingStyle, chapterCount: initialTemplate.chapterCount, targetPageCount: initialTemplate.targetPageCount } : baseForm);
  const update = <K extends keyof BookForm>(key: K, value: BookForm[K]) => setForm((current) => ({ ...current, [key]: value }));
  const next = () => { if (step === 1 && (!form.title.trim() || !form.idea.trim())) return setError("Add a working title and a few words about your book idea."); if (step === 2 && !form.targetAudience.trim()) return setError("Tell us who this book is meant to help or reach."); setError(""); setStep((value) => Math.min(4, value + 1)); };
  const submit = async () => { setWorking(true); setError(""); try { await onCreate(form); } catch { setError("We could not build the blueprint. Please try again."); setWorking(false); } };
  const steps = ["Book idea", "Ideal reader", "Voice & style", "Book plan"];
  return <div className="modal-backdrop"><section className="wizard-modal" role="dialog" aria-modal="true" aria-label="Start a new book">
    <aside className="wizard-aside"><div className="brand brand-light"><span className="brand-mark">CL</span><span><strong>Clarity Loop</strong><small>AI BOOK STUDIO</small></span></div><div><p className="eyebrow">YOUR BOOK BEGINS HERE</p><h2>Let’s turn your idea into a clear plan.</h2><p>Nothing needs to be perfect. You can revise every detail before writing.</p></div><ol>{steps.map((label, index) => <li className={step === index + 1 ? "active" : step > index + 1 ? "done" : ""} key={label}><span>{step > index + 1 ? <Check size={14} /> : index + 1}</span><em>{label}</em></li>)}</ol><blockquote>“Start with what matters. We’ll help shape what comes next.”</blockquote></aside>
    <div className="wizard-content"><div className="wizard-top"><span>Step {step} of 4</span><button aria-label="Close book setup" onClick={onClose}><X /></button></div>
      {step === 1 && <div className="wizard-form"><p className="eyebrow">THE BIG IDEA</p><h2>What book are you ready to create?</h2><p>Begin with a working title and the message, story, or outcome you want to share.</p><label>Working title<input autoFocus value={form.title} onChange={(event) => update("title", event.target.value)} placeholder="e.g. The Courage to Begin" /></label><label>Subtitle <small>Optional</small><input value={form.subtitle} onChange={(event) => update("subtitle", event.target.value)} placeholder="A practical guide to moving forward" /></label><label>Your book idea<textarea value={form.idea} onChange={(event) => update("idea", event.target.value)} placeholder="Describe what the book is about, why it matters, and what you want readers to take away." /></label></div>}
      {step === 2 && <div className="wizard-form"><p className="eyebrow">YOUR READER</p><h2>Who is waiting for this book?</h2><p>Picture the person who most needs your message. Specific is better than broad.</p><label>My ideal reader is…<textarea autoFocus value={form.targetAudience} onChange={(event) => update("targetAudience", event.target.value)} placeholder="e.g. A busy professional who knows something needs to change, but is not sure where to begin." /></label><label>Book type<select value={form.genre} onChange={(event) => update("genre", event.target.value)}><option>Self-Help</option><option>Business</option><option>Memoir</option><option>Christian Devotional</option><option>Biography</option><option>Children’s Book</option><option>Other Nonfiction</option></select></label><div className="tip-card"><Sparkles size={18} /><span><strong>Why this matters</strong>A clear reader helps every chapter feel more personal, focused, and useful.</span></div></div>}
      {step === 3 && <div className="wizard-form"><p className="eyebrow">VOICE & STYLE</p><h2>How should your book sound?</h2><p>Choose a starting voice. Your Book DNA will carry it across every chapter.</p><div className="field-pair"><label>Tone<select value={form.tone} onChange={(event) => update("tone", event.target.value)}><option>Encouraging and clear</option><option>Warm and hopeful</option><option>Confident and authoritative</option><option>Personal and honest</option><option>Playful and kind</option></select></label><label>Writing style<select value={form.writingStyle} onChange={(event) => update("writingStyle", event.target.value)}><option>Practical and story-led</option><option>Reflective and accessible</option><option>Narrative and vivid</option><option>Insightful and example-driven</option><option>Simple and visual</option></select></label></div><label>How would you like AI to help?<div className="assistance-grid">{([['full','Do everything for me','Create the structure and draft each chapter.'],['guided','Guide me chapter by chapter','Review and approve as your book grows.'],['assistive','I’ll write; AI will improve','Use AI for editing, expansion, and polish.']] as [AIAssistanceLevel,string,string][]).map(([value,title,copy]) => <button className={form.aiAssistanceLevel === value ? "selected" : ""} onClick={() => update("aiAssistanceLevel", value)} key={value}><span>{form.aiAssistanceLevel === value && <Check size={13} />}</span><strong>{title}</strong><small>{copy}</small></button>)}</div></label></div>}
      {step === 4 && <div className="wizard-form"><p className="eyebrow">YOUR BOOK PLAN</p><h2>Choose a comfortable starting shape.</h2><p>Clarity Loop will turn these choices into an editable blueprint and table of contents.</p><div className="field-pair"><label>Number of chapters<div className="number-control"><button onClick={() => update("chapterCount", Math.max(5, form.chapterCount - 1))}>−</button><strong>{form.chapterCount}</strong><button onClick={() => update("chapterCount", Math.min(30, form.chapterCount + 1))}>+</button></div></label><label>Target page count<input type="number" min="40" max="600" value={form.targetPageCount} onChange={(event) => update("targetPageCount", Number(event.target.value))} /></label></div><label>Chapter size<div className="size-options">{([['short','Short'],['medium','Medium'],['long','Long'],['auto','Let AI decide']] as [ChapterSizePreference,string][]).map(([value,label]) => <button className={form.chapterSizePreference === value ? "selected" : ""} onClick={() => update("chapterSizePreference", value)} key={value}>{label}</button>)}</div></label><div className="plan-summary"><span><small>Estimated manuscript</small><strong>About {form.targetPageCount * 250 / 1000}k words</strong></span><span><small>Estimated reading time</small><strong>{Math.round(form.targetPageCount * 1.5)} minutes</strong></span></div></div>}
      {error && <p className="form-error">{error}</p>}<div className="wizard-actions"><button className="secondary-button" onClick={() => step === 1 ? onClose() : setStep(step - 1)}><ArrowLeft size={16} /> {step === 1 ? "Cancel" : "Back"}</button>{step < 4 ? <button className="primary-button" onClick={next}>Continue <ArrowRight size={16} /></button> : <button className="primary-button" onClick={submit} disabled={working}><Sparkles size={16} /> {working ? "Building your blueprint…" : "Create My Blueprint"}</button>}</div>
    </div>
  </section></div>;
}
