import type { GenreProfile, OpeningStyle } from "./types";

const profiles: Record<string, GenreProfile> = {};

function profile(label: string, creativeMode: string, readerExpectation: string, narrativeStructure: string, requiredElements: string[], forbiddenPatterns: string[], preferredChapterPatterns: string[], toneGuidance: string, openingStyles: OpeningStyle[], exampleTypes: string[], chapterPurposeStyle: string, coverMoodHints: string[]): GenreProfile {
  return { genreId: label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""), label, creativeMode, readerExpectation, narrativeStructure, requiredElements, forbiddenPatterns, preferredChapterPatterns, toneGuidance, openingStyles, exampleTypes, chapterPurposeStyle, coverMoodHints };
}

export const GENRE_PROFILES: GenreProfile[] = [
  profile("Biography", "life_story", "A human journey shaped by meaningful events, relationships, adversity, growth, contribution, and legacy.", "Chronological or thematic life-stage structure", ["early life or origin context", "family or community influence", "defining moments", "challenges and setbacks", "relationships and mentors", "personal growth", "public contribution or legacy"], ["business framework language", "corporate consulting tone", "generic productivity advice", "chapter titles that sound like business strategy", "overuse of implementation frameworks"], ["origin", "formation", "conflict", "turning point", "growth", "legacy"], "Human, reflective, narrative, grounded, emotionally aware, respectful.", ["scenario", "observation", "contrast"], ["remembered scenes", "family stories", "turning points", "historical context"], "Reveal what a life meant through specific moments and consequences.", ["archival warmth", "human portraiture", "time and memory"]),
  profile("Memoir", "memory_journey", "An intimate, emotionally honest journey through memory, meaning, and personal change.", "Thematic or braided first-person memory arc", ["specific memories", "sensory detail", "emotional honesty", "reflection", "change over time"], ["corporate frameworks", "detached biography voice", "generic life advice"], ["memory", "silence", "rupture", "reckoning", "return"], "Intimate, candid, reflective, vivid, and emotionally precise.", ["scenario", "observation", "direct_claim"], ["lived scenes", "private realizations", "relationships"], "Turn remembered experience into earned meaning without flattening complexity.", ["memory fragments", "personal artifacts", "intimate atmosphere"]),
  profile("Business & Professional Development", "framework_instruction", "A useful thesis supported by frameworks, cases, practical application, and strategic insight.", "Problem to principle to framework to implementation", ["clear thesis", "reader problem", "framework or model", "case examples", "application guidance", "strategic takeaway"], ["fictional plot structure unless requested", "overly sentimental memoir tone", "generic motivation without operational usefulness"], ["problem", "principle", "model", "application", "scale"], "Clear, authoritative, practical, strategic, credible.", ["problem_statement", "case_example", "direct_claim"], ["case studies", "operating decisions", "measurable outcomes"], "Advance one practical claim and show the reader how to use it.", ["confident geometry", "systems", "modern authority"]),
  profile("Leadership", "leadership_practice", "Insight into judgment, responsibility, trust, teams, and decisions under real conditions.", "Leadership tension to principle to practice", ["leadership dilemma", "human stakes", "decision principle", "team example", "reflective practice"], ["empty inspiration", "command-and-control clichés", "unearned certainty"], ["responsibility", "trust", "decision", "culture", "legacy"], "Wise, direct, humane, credible, and grounded in practice.", ["scenario", "case_example", "contrast"], ["team decisions", "culture moments", "leadership tradeoffs"], "Connect leadership character to observable choices and consequences.", ["human authority", "shared direction", "quiet confidence"]),
  profile("Technology & Innovation", "systems_exploration", "A clear explanation of change, possibility, risk, systems, and responsible adoption.", "Emerging tension to system insight to responsible application", ["technical context", "human impact", "tradeoffs", "examples", "responsible application"], ["hype without evidence", "robot clichés", "implementation claims without context"], ["shift", "system", "experiment", "risk", "future"], "Curious, precise, accessible, forward-looking, and responsible.", ["contrast", "case_example", "observation"], ["technology shifts", "prototypes", "adoption decisions"], "Make complexity understandable while preserving consequences and uncertainty.", ["intelligent systems", "subtle futurism", "human-centered technology"]),
  profile("Self-Help", "guided_transformation", "A compassionate path from a recognizable struggle toward practical personal change.", "Recognition to reframing to practice to integration", ["reader struggle", "compassionate insight", "practical exercise", "progression", "encouragement"], ["shaming language", "instant transformation promises", "clinical claims without support"], ["recognition", "release", "practice", "trust", "integration"], "Encouraging, clear, compassionate, practical, and honest.", ["question", "scenario", "observation"], ["relatable moments", "guided reflections", "small practices"], "Help the reader feel seen, then offer a usable next step.", ["open path", "calm movement", "hopeful clarity"]),
  profile("Faith & Spiritual Growth", "spiritual_growth", "Testimony, restoration, calling, scripture-aware reflection, and movement toward deeper faith.", "Testimony or devotional movement from struggle to grace to calling", ["spiritual tension", "testimony", "grace or restoration", "calling", "reverent reflection"], ["corporate consulting tone", "transactional faith claims", "careless proof-texting"], ["valley", "grace", "surrender", "restoration", "calling"], "Reverent, restorative, spiritually grounded, warm, and testimony-aware.", ["scenario", "observation", "question"], ["testimony", "scripture-aware reflection", "moments of surrender"], "Invite spiritual recognition and faithful response without reducing mystery.", ["light through shadow", "restoration", "sacred quiet"]),
  profile("Fiction", "story_world", "Characters, stakes, conflict, setting, pacing, scenes, dialogue, and emotional payoff.", "Scene-driven narrative arc", ["main character", "central conflict", "stakes", "setting", "turning points", "emotional arc", "resolution or cliffhanger"], ["business framework chapters", "instructional nonfiction tone", "chapter titles that sound like essays"], ["arrival", "threat", "choice", "reversal", "consequence", "resolution"], "Immersive, scene-aware, emotionally alive, story-driven.", ["scenario", "contrast", "observation"], ["scenes", "dialogue", "sensory setting", "character choices"], "Change the story situation through action, discovery, and consequence.", ["cinematic atmosphere", "symbolic object", "story-world tension"]),
  profile("Children’s Story", "imaginative_story", "A vivid, age-appropriate adventure with emotional safety, repetition, wonder, and a memorable lesson.", "Simple quest or problem-resolution story arc", ["child-centered character", "clear desire", "playful obstacle", "visual moments", "reassuring resolution"], ["adult abstraction", "dense exposition", "frightening detail without reassurance"], ["wonder", "discovery", "mischief", "courage", "homecoming"], "Playful, warm, visual, rhythmic, and age-appropriate.", ["scenario", "question", "observation"], ["visual action", "playful dialogue", "repetition"], "Create one vivid story movement a child can follow and remember.", ["bright wonder", "friendly character", "storybook texture"]),
  profile("Workbook / Training Manual", "applied_practice", "Clear lessons, exercises, prompts, checklists, and immediate application.", "Lesson to demonstration to exercise to reflection", ["learning objective", "worked example", "exercise", "reflection prompt", "checklist", "application section"], ["passive inspiration", "long narrative without application", "unclear action"], ["clarify", "map", "practice", "review", "apply"], "Direct, supportive, practical, structured, and action-oriented.", ["problem_statement", "direct_claim", "case_example"], ["worked examples", "prompts", "checklists", "practice scenarios"], "Teach one skill and give the reader a concrete way to practice it.", ["organized tools", "workshop energy", "clear progression"]),
  profile("Screenplay / Adaptation", "screen_story", "Visual storytelling, playable scenes, character objectives, conflict, reversals, and cinematic momentum.", "Sequence-based dramatic arc", ["visual premise", "character objective", "scene conflict", "turning points", "set pieces", "resolution"], ["essay chapters", "internal explanation that cannot be dramatized", "generic business structure"], ["opening image", "inciting incident", "reversal", "crisis", "climax"], "Visual, lean, dramatic, cinematic, and action-aware.", ["scenario", "contrast", "direct_claim"], ["scenes", "visual motifs", "dialogue beats", "set pieces"], "Create a playable dramatic movement with a visible change in stakes.", ["cinematic frame", "dramatic silhouette", "visual tension"]),
];

for (const item of GENRE_PROFILES) profiles[item.label.toLowerCase()] = item;
const aliases: Record<string, string> = { business: "Business & Professional Development", nonfiction: "Business & Professional Development", faith: "Faith & Spiritual Growth", spirituality: "Faith & Spiritual Growth", workbook: "Workbook / Training Manual", training: "Workbook / Training Manual", "children’s book": "Children’s Story", "children's book": "Children’s Story", screenplay: "Screenplay / Adaptation", adaptation: "Screenplay / Adaptation" };

export function getGenreProfile(bookType?: string): GenreProfile {
  const normalized = (bookType || "Self-Help").trim().toLowerCase();
  const exact = profiles[normalized];
  if (exact) return exact;
  const alias = Object.entries(aliases).find(([key]) => normalized.includes(key));
  if (alias) return profiles[alias[1].toLowerCase()];
  const partial = GENRE_PROFILES.find((item) => normalized.includes(item.label.toLowerCase()) || item.label.toLowerCase().includes(normalized));
  return partial || profiles["self-help"];
}
