import type { Book, BookPositioning, MonetizationPackage } from "./types";

export function generateMonetizationPackage(book: Book, positioning: BookPositioning): MonetizationPackage {
  const fiction = /fiction|romance|thriller|mystery|fantasy|drama|sci-fi|novel/i.test(`${book.genre} ${book.bookDna.bookType}`);
  const faith = /faith|christian|spiritual|devotional|ministry/i.test(book.genre);
  if (fiction) return { workshopOutline: ["Author craft conversation", "Character and theme exploration", "Reader Q&A and guided discussion"], courseOutline: ["Inside the story world", "Character choices and consequences", "From first draft to finished novel"], webinarOutline: ["Story origins", "Reading and scene breakdown", "Audience Q&A"], keynoteTopics: ["Why stories help us rehearse difficult choices", `The themes behind ${book.title}`], speakerOneSheetCopy: `${book.authorName} offers reader events and craft conversations rooted in ${book.title}, its characters, themes, and creative process.`, consultingOffer: "Not recommended for this fiction project. Prioritize reader experiences, rights, and adaptation opportunities.", leadMagnetIdeas: ["Bonus scene", "Character dossier", "Book-club discussion guide", "Story-world map"], emailNurtureSequence: ["Welcome to the story world", "Meet a character", "Behind a pivotal scene", "Book-club invitation"], coachingPackageIdeas: ["Small-group fiction craft clinic", "Book-club author visit"], corporateTrainingAngle: "Not recommended unless the author intentionally develops a story-based learning adaptation.", };
  const setting = faith ? "ministry, small-group, and speaking" : "workshop, consulting, speaking, and training";
  return { workshopOutline: [`Name the challenge facing ${book.targetAudience}`, `Teach the ${book.bookDna.themes.slice(0, 3).join(" / ") || "core book"} framework`, "Apply the framework to a live scenario", "Commit to a next action"], courseOutline: book.chapters.slice(0, 6).map((chapter) => `${chapter.title}: ${chapter.summary || chapter.readerTakeaway || "guided lesson and application"}`), webinarOutline: ["Why this problem persists", `The central promise: ${positioning.readerPromise}`, "Three book-derived insights", "A practical implementation invitation"], keynoteTopics: [`From idea to action: ${positioning.readerPromise}`, ...book.bookDna.themes.slice(0, 3).map((theme) => `${theme}: what readers and leaders need now`)], speakerOneSheetCopy: `${book.authorName} speaks to ${book.targetAudience} about ${book.bookDna.themes.slice(0, 3).join(", ")}. Each session translates ${book.title} into an audience-aware experience with practical next steps.`, consultingOffer: faith ? "Offer a facilitated ministry workshop or study-series design engagement tied directly to the book's themes." : `Offer a fixed-scope diagnostic and implementation workshop that helps ${book.targetAudience} apply the book's central framework.`, leadMagnetIdeas: ["Chapter companion worksheet", "Readiness self-assessment", "Five-day email challenge", faith ? "Small-group discussion guide" : "Executive briefing"], emailNurtureSequence: ["Deliver the resource", "Name the cost of the current problem", "Teach one book framework", "Share a relevant example", `Invite the reader into a ${setting} next step`], coachingPackageIdeas: faith ? ["Four-week guided study cohort", "Ministry leader facilitation package"] : ["Four-session implementation sprint", "Team leadership cohort"], corporateTrainingAngle: faith ? "Adapt only for values-aligned organizations with explicit audience fit; do not present spiritual claims as corporate performance guarantees." : `Translate the book into a half-day team workshop with scenarios, worksheets, and a 30-day application plan for ${book.targetAudience}.` };
}
