import type { Book, BookTemplate } from "./types";

export const templates: BookTemplate[] = [
  { id: "self-help", name: "Self-Help Guide", eyebrow: "Most popular", description: "Turn your expertise into a practical, step-by-step transformation.", icon: "Sparkles", color: "lilac", genre: "Self-Help", audience: "People ready to make a meaningful change", tone: "Encouraging", writingStyle: "Practical and story-led", chapterCount: 10, length: "Standard · 30,000 words" },
  { id: "devotional", name: "Christian Devotional", eyebrow: "Faith & reflection", description: "Create warm daily readings with scripture, reflection, and prayer.", icon: "Heart", color: "peach", genre: "Christian Devotional", audience: "Readers seeking daily spiritual encouragement", tone: "Warm and hopeful", writingStyle: "Reflective and accessible", chapterCount: 14, length: "Short · 15,000 words" },
  { id: "memoir", name: "Memoir", eyebrow: "Your story", description: "Shape your life experiences into an honest and memorable narrative.", icon: "Feather", color: "blue", genre: "Memoir", audience: "Readers who connect through real-life stories", tone: "Personal and honest", writingStyle: "Narrative and vivid", chapterCount: 12, length: "Standard · 30,000 words" },
  { id: "business", name: "Business Book", eyebrow: "Build authority", description: "Share your method, point of view, and real-world lessons with clarity.", icon: "BriefcaseBusiness", color: "green", genre: "Business", audience: "Leaders, founders, and working professionals", tone: "Confident and clear", writingStyle: "Insightful and example-driven", chapterCount: 10, length: "Standard · 30,000 words" },
  { id: "biography", name: "Biography", eyebrow: "A life in full", description: "Tell a compelling life story with context, milestones, and meaning.", icon: "UserRound", color: "gold", genre: "Biography", audience: "General readers interested in an inspiring life", tone: "Thoughtful", writingStyle: "Chronological and cinematic", chapterCount: 12, length: "Long · 50,000 words" },
  { id: "children", name: "Children’s Book", eyebrow: "Big imagination", description: "Build a simple, playful story around a memorable lesson.", icon: "Rainbow", color: "rose", genre: "Children’s Book", audience: "Children ages 6–9 and their caregivers", tone: "Playful and kind", writingStyle: "Simple and visual", chapterCount: 8, length: "Short · 8,000 words" },
];

export const sampleBooks: Book[] = [
  {
    id: "clear-way-forward",
    title: "The Clear Way Forward",
    subtitle: "A practical guide to making confident decisions",
    genre: "Self-Help",
    audience: "Busy professionals who feel stuck or overwhelmed",
    tone: "Encouraging",
    writingStyle: "Practical and story-led",
    bookLength: "Standard · 30,000 words",
    status: "Writing",
    autoMode: false,
    progress: 42,
    updatedAt: "Today, 9:42 AM",
    color: "violet",
    bookDNA: {
      tone: "Encouraging, calm, and quietly confident",
      audience: "Busy professionals who feel stuck or overwhelmed",
      readingLevel: "Clear and conversational",
      voice: "A trusted guide sitting across the table",
      themes: ["clarity", "courage", "small steps", "self-trust"],
      styleRules: ["Use short examples", "End chapters with a reflection", "Avoid jargon"],
    },
    chapters: [
      { id: "c1", chapterNumber: 1, title: "When the Path Feels Foggy", summary: "Open with the emotional cost of uncertainty and show why clarity is a practice, not a personality trait.", targetWordCount: 2200, content: "There is a particular kind of tiredness that comes from carrying a decision you have not made. It follows you from room to room, quietly asking for attention.\n\nMost of us assume clarity arrives like a flash of light. In practice, it is more often built through a series of small, honest questions. The goal is not to see the entire road. It is to see enough of the next step to begin.", status: "Draft ready", locked: true },
      { id: "c2", chapterNumber: 2, title: "The Noise Around the Decision", summary: "Help readers separate their own priorities from outside expectations, urgency, and fear.", targetWordCount: 2400, content: "", status: "Ready to write", locked: false },
      { id: "c3", chapterNumber: 3, title: "Name What Matters Most", summary: "Introduce a simple values filter for narrowing choices without overthinking every possibility.", targetWordCount: 2500, content: "", status: "Ready to write", locked: false },
      { id: "c4", chapterNumber: 4, title: "Make the Smallest Honest Move", summary: "Turn insight into action with a low-risk next-step practice readers can use immediately.", targetWordCount: 2300, content: "", status: "Not started", locked: false },
      { id: "c5", chapterNumber: 5, title: "Trust the Evidence You Create", summary: "Show how action produces useful information and rebuilds trust in personal judgment.", targetWordCount: 2400, content: "", status: "Not started", locked: false },
    ],
  },
  {
    id: "lead-with-room",
    title: "Lead With Room",
    subtitle: "A healthier way to build teams that thrive",
    genre: "Business",
    audience: "New and growing team leaders",
    tone: "Warm and authoritative",
    writingStyle: "Example-driven",
    bookLength: "Standard · 30,000 words",
    status: "Planning",
    autoMode: true,
    progress: 18,
    updatedAt: "Yesterday",
    color: "teal",
    bookDNA: { tone: "Warm and authoritative", audience: "New team leaders", readingLevel: "Conversational", voice: "Experienced mentor", themes: ["leadership", "trust", "space"], styleRules: ["Use workplace stories", "Keep advice practical"] },
    chapters: [],
  },
  {
    id: "morning-mercy",
    title: "Morning Mercy",
    subtitle: "Thirty reflections for beginning again",
    genre: "Christian Devotional",
    audience: "Readers seeking gentle daily encouragement",
    tone: "Hopeful",
    writingStyle: "Reflective",
    bookLength: "Short · 15,000 words",
    status: "Complete",
    autoMode: false,
    progress: 100,
    updatedAt: "May 28",
    color: "coral",
    bookDNA: { tone: "Hopeful and gentle", audience: "Faith-centered readers", readingLevel: "Accessible", voice: "Compassionate companion", themes: ["mercy", "renewal", "grace"], styleRules: ["Include a prayer", "Keep entries brief"] },
    chapters: [],
  },
];
